version: '3.4'
services:
  server-1:
    image: ealen/echo-server:latest
    restart: always
    environment:
      - ENABLE__ENVIRONMENT = false

  server-2:
    image: ealen/echo-server:latest
    restart: always
    environment:
      - ENABLE__ENVIRONMENT = false

  server-3:
    image: ealen/echo-server:latest
    restart: always
    environment:
      - ENABLE__ENVIRONMENT = false
#Serving as Reverse Proxy and Load Balancer
  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 9999:9999

  southface:
    image: southface/demo:1.9
    ports:
      - 3000:3000
    working_dir: /FEC-South-Face
    tty: true

  # southface:
  #   image: node:16-bullseye
  #   container_name: southface
  #   entrypoint: /bin/sh
  #   ports:
  #     - 8080:8080
  #   working_dir: /app
  #   volumes:
  #     - type: bind
  #       source: ./
  #       target: /app
  #   tty: true
